CONFIG_GPIO=y
CONFIG_PRINTK=y

# CubeMot modules
CONFIG_NEWLIB_LIBC=n
CONFIG_PICOLIBC=n

# Module enable flags
CONFIG_MODULE_LED_CONTROLLER_ENABLE=y
CONFIG_MODULE_BUTTON_DETECTOR_ENABLE=y
CONFIG_MODULE_BLINK_ENABLE=y

# Thread stack sizes
CONFIG_MAIN_STACK_SIZE=1024

# ADC for FOC
CONFIG_ADC=y
CONFIG_LOG=y
