name: Code Format Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  c-cpp:
    name: C/C++ Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: '.'
          extensions: 'c,h,cpp,hpp,cc,hh,cxx,hxx'
          clangFormatVersion: 19
          style: file

  python:
    name: Python Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          src: >-
            ./tools/
          args: "format --check --diff"
